sudo: required

language: node_js
node_js:
  - "7"

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_script:
  - npm install -g gulp

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # create the environment
  - npm run dc

  # logging
  - docker ps

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bundyfx/express-web-api-example;
    fi