version: "2"

services:
  mongodb:
    image: mongo
    expose:
      - 27017

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
    depends_on:
      - "mongodb"

  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - "mongodb"